<?php
// service schema for EOS connections
// note the hidden=true flag prevents this from appearing in the editor
// since the connections will be auto-generated by eos-mc
return [
    "Sample" => ["type" =>"group","fields"=>[
        "color" => ["type"=>"enum","valid"=>["red","green","blue"]],
        "boolean" => ["type"=>"enum","value"=>"yes","valid"=>["yes","no"]],
        "number" => ["type"=>"number","valid"=>["min"=>0,"max"=>100]],
        "messages" => ["type"=>"group","fields"=> [
                "loginmessage" => ["type"=>"text","value"=>"Please Login"],
                "registermessage" => ["type"=>"text","value"=>"New Account Register"],
                "systemerror" => ["type"=>"text","valid"=>"System error, try again later"]
            ]
        ]
    ]]
];
